spring:
  application:
    name: consumer-example

dubbo:
  application:
    name: consumer-example
  registry:
    address: nacos://192.168.1.244:8848
  protocol:
    serialization: kryo
    name: dubbo
    port: -1
